"""add_application_constraints

Revision ID: 2b9ff9dc5ace
Revises: 3596dbc2ff4a
Create Date: 2026-08-03 10:54:28.372111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9ff9dc5ace'
down_revision: Union[str, Sequence[str], None] = '3596dbc2ff4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_opportunity', 'applications', ['student_id', 'opportunity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_opportunity', 'applications', type_='unique')
    # ### end Alembic commands ###
